### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by rnshah9**

### CODE REVIEW

**Comment by rnshah9** [comment]
Added extra include flag to fix the build.

**Review by xansec — CHANGES_REQUESTED** [review]
This target seems to be failing on every input. Can we revisit/improve the harnesses? Please make the requested changes.

**Comment by rnshah9** [comment]
I'm not very familiar with libFuzzer, but this seems like a possible Mayhem issue to me.

When I run the fuzzer `/cmd` locally (i.e. in a Docker container), I consistently see this output before the run begins:
```
==18==AddressSanitizer: failed to intercept '__isoc99_printf'
'==18==AddressSanitizer: failed to intercept '__isoc99_sprintf'
'==18==AddressSanitizer: failed to intercept '__isoc99_snprintf'
'==18==AddressSanitizer: failed to intercept '__isoc99_fprintf'
'==18==AddressSanitizer: failed to intercept '__isoc99_vprintf'
'==18==AddressSanitizer: failed to intercept '__isoc99_vsprintf'
'==18==AddressSanitizer: failed to intercept '__isoc99_vsnprintf'
'==18==AddressSanitizer: failed to intercept '__isoc99_vfprintf'
'==18==AddressSanitizer: failed to intercept 'crypt'
'==18==AddressSanitizer: failed to intercept 'crypt_r'
'==18==AddressSanitizer: failed to intercept '__cxa_rethrow_primary_exception'
'==18==AddressSanitizer: libc interceptors initialized
|| `[0x10007fff8000, 0x7fffffffffff]` || HighMem    ||
...
```
The same "failed to intercept" message appears in all the defects found by Mayhem, e.g. [this one](https://mayhem.forallsecure.com/rnshah9/wireguard-tools/cmd/-/defects/312509).

But the fuzzer exits with code 0. It also exits with code 0 when I download the crashing test case from Mayhem and run it locally (and it does not find a crash). Yet Mayhem shows:

image

My guess is that this is a warning message that Mayhem is treating as an error. This [thread](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58680) may be related.

Is this plausible?

**Comment by xansec** [comment]
This should be fixed.
https://mayhem.forallsecure.com/rnshah9/wireguard-tools/cmd/18

Merging.

**Comment by rnshah9** [comment]
Awesome, thanks for looking into it!

**Pull request merged**
